"use client";
import {useCallback,useEffect,useState} from "react";
type Album={id:number;platform:string;title:string;url:string;age_evidence:string;age_confidence:string;sale_type?:number|null;download_status:string;downloaded_tracks?:number;total_tracks?:number;reason?:string;last_seen?:string};
export default function Home(){
 const [albums,setAlbums]=useState<Album[]>([]);const [refreshing,setRefreshing]=useState(false);const [message,setMessage]=useState("");
 const load=useCallback(async()=>{const response=await fetch("/api/kids/albums",{cache:"no-store"});if(!response.ok)throw new Error("目录读取失败");const data=await response.json();setAlbums(data.albums)},[]);
 useEffect(()=>{load().catch(e=>setMessage(e.message))},[load]);
 const busy=albums.some(x=>x.download_status==="queued"||x.download_status==="running");
 useEffect(()=>{if(!busy)return;const timer=setInterval(()=>load().catch(()=>{}),3000);return()=>clearInterval(timer)},[busy,load]);
 const downloadLabel=(x:Album)=>x.download_status==="not_downloaded"?"下载":x.download_status==="queued"?"排队中":x.download_status==="running"?`下载中 ${x.downloaded_tracks??0}/${x.total_tracks??0}`:x.download_status==="partial"?"部分完成":x.download_status==="skipped_paid"?"付费跳过":x.download_status==="failed"?"重试":x.download_status==="done"?"已下载":x.download_status==="unavailable"?"已下架":`未知(${x.download_status})`;
 const refresh=async()=>{setRefreshing(true);setMessage("");try{const response=await fetch("/api/kids/refresh",{method:"POST"});const data=await response.json();if(!response.ok)throw new Error(data.detail||"获取失败");await load();setMessage(`已获取 ${data.count} 个最新候选`)}catch(e){setMessage(e instanceof Error?e.message:"获取失败")}finally{setRefreshing(false)}};
 const queue=async(id:number)=>{await fetch(`/api/kids/albums/${id}/download`,{method:"POST"});await load()};
 // last_seen 为后端本地时间 ISO 字符串，切片读取避免跨时区换算偏移。
 const stamp=albums.map(x=>x.last_seen??"").sort().at(-1)??"";
 const heading=stamp?`${+stamp.slice(0,4)}年${+stamp.slice(5,7)}月精选`:"本月精选";
 const updated=stamp&&`更新于 ${+stamp.slice(5,7)}月${+stamp.slice(8,10)}日 ${stamp.slice(11,16)}`;
 return <main><a className="back" href="/">← 返回首页</a><header><div><span>宝宝音频库 · 0–1岁</span><h1>{heading}</h1><small>只显示平台明确年龄依据</small>{updated&&<small>{updated}</small>}</div><button className="refresh" disabled={refreshing} onClick={refresh}>{refreshing?"正在获取…":"获取最新"}</button></header>{message&&<p className="message">{message}</p>}{albums.length===0&&!refreshing&&<section className="empty"><h2>还没有本月候选</h2><p>点击“获取最新”，从平台公开目录生成列表。</p></section>}<section>{albums.map(x=><article key={x.id} className={x.download_status==="unavailable"?"offline":""}><div><b>{x.platform}</b><a href={x.url} target="_blank" rel="noreferrer">{x.title}{x.sale_type===0&&<span className="badge free">免费</span>}{x.sale_type===1&&<span className="badge vip">会员畅听</span>}{x.sale_type==null&&<span className="badge unknown" title="该平台未提供付费信息">付费未知</span>}</a><small>{x.age_evidence} · {x.age_confidence}可信</small>{x.reason&&<small>{x.reason}</small>}</div><button disabled={x.download_status!=="not_downloaded"&&x.download_status!=="failed"&&x.download_status!=="needs_authorization"} onClick={()=>queue(x.id)}>{downloadLabel(x)}</button></article>)}</section></main>}