"use client";
import {useCallback,useEffect,useState} from "react";
type Album={id:number;platform:string;title:string;url:string;age_evidence:string;age_confidence:string;download_status:string;reason?:string};
export default function Home(){
 const [albums,setAlbums]=useState<Album[]>([]);const [refreshing,setRefreshing]=useState(false);const [message,setMessage]=useState("");
 const load=useCallback(async()=>{const response=await fetch("/api/kids/albums",{cache:"no-store"});if(!response.ok)throw new Error("目录读取失败");const data=await response.json();setAlbums(data.albums)},[]);
 useEffect(()=>{load().catch(e=>setMessage(e.message))},[load]);
 const refresh=async()=>{setRefreshing(true);setMessage("");try{const response=await fetch("/api/kids/refresh",{method:"POST"});const data=await response.json();if(!response.ok)throw new Error(data.detail||"获取失败");await load();setMessage(`已获取 ${data.count} 个最新候选`)}catch(e){setMessage(e instanceof Error?e.message:"获取失败")}finally{setRefreshing(false)}};
 const queue=async(id:number)=>{await fetch(`/api/kids/albums/${id}/download`,{method:"POST"});await load()};
 return <main><header><div><span>宝宝音频库 · 0–1岁</span><h1>本月精选</h1><small>只显示平台明确年龄依据</small></div><button className="refresh" disabled={refreshing} onClick={refresh}>{refreshing?"正在获取…":"获取最新"}</button></header>{message&&<p className="message">{message}</p>}{albums.length===0&&!refreshing&&<section className="empty"><h2>还没有本月候选</h2><p>点击“获取最新”，从平台公开目录生成列表。</p></section>}<section>{albums.map(x=><article key={x.id}><div><b>{x.platform}</b><a href={x.url} target="_blank" rel="noreferrer">{x.title}</a><small>{x.age_evidence} · {x.age_confidence}可信</small>{x.reason&&<small>{x.reason}</small>}</div><button disabled={x.download_status!=="not_downloaded"} onClick={()=>queue(x.id)}>{x.download_status==="not_downloaded"?"下载":x.download_status==="needs_authorization"?"需授权":"已下载"}</button></article>)}</section></main>}