const { chromium } = require('C:/Users/Administrator/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert = require('node:assert/strict');
(async () => {
 const browser = await chromium.launch({executablePath:'C:/Users/Administrator/AppData/Local/ms-playwright/chromium-1243/chrome-win64/chrome.exe',headless:true});
 const context = await browser.newContext({viewport:{width:1280,height:900}, permissions:['clipboard-read','clipboard-write']});
 const page = await context.newPage();
 const errors=[]; page.on('pageerror', e=>errors.push(e.message));
 await page.goto('http://localhost:3006/rss');
 await page.getByRole('button',{name:'订阅渠道',exact:true}).click();
 const dialog=page.getByRole('dialog');
 await dialog.getByRole('heading',{name:'新闻联播服务',exact:true}).waitFor();
 await dialog.getByRole('button',{name:'复制链接',exact:true}).first().click();
 await page.getByRole('button',{name:'✓ 已复制',exact:true}).waitFor();
 const copied=await page.evaluate(()=>navigator.clipboard.readText());
 assert.equal(new URL(copied).searchParams.get('channel'),'xinwen');
 assert.equal(new URL(copied).searchParams.get('token'),'test-token');
 await dialog.getByRole('button',{name:'管理渠道 →',exact:true}).click();
 await dialog.getByRole('button',{name:'＋ 新增渠道',exact:true}).click();
 await dialog.getByLabel('服务名称',{exact:true}).fill('界面验证渠道');
 await dialog.getByLabel('渠道标识',{exact:false}).fill('ui-smoke');
 await dialog.getByLabel('说明',{exact:true}).fill('本地测试');
 await dialog.getByRole('button',{name:'保存渠道',exact:true}).click();
 await dialog.getByRole('heading',{name:'界面验证渠道',exact:true}).waitFor();
 const row=dialog.locator('div.py-4').filter({has:page.getByRole('heading',{name:'界面验证渠道',exact:true})});
 await row.getByRole('button',{name:'编辑',exact:true}).click();
 await dialog.getByLabel('服务名称',{exact:true}).fill('改名验证渠道');
 await dialog.getByRole('button',{name:'保存渠道',exact:true}).click();
 const renamed=dialog.locator('div.py-4').filter({has:page.getByRole('heading',{name:'改名验证渠道',exact:true})});
 await renamed.getByRole('button',{name:'停用',exact:true}).click();
 await renamed.getByRole('button',{name:'确认停用',exact:true}).click();
 await renamed.getByRole('button',{name:'恢复',exact:true}).waitFor();
 await renamed.getByRole('button',{name:'恢复',exact:true}).click();
 await renamed.getByRole('button',{name:'停用',exact:true}).waitFor();
 await dialog.getByRole('button',{name:'关闭',exact:true}).click();
 await page.getByRole('button',{name:'🔌 对接',exact:true}).click();
 await page.getByLabel('选择推送渠道').selectOption('ui-smoke');
 await page.getByRole('heading',{name:'Python',exact:true}).waitFor();
 const code=await page.getByRole('heading',{name:'Python',exact:true}).locator('..').locator('pre').textContent();
 assert.ok(code.includes('\n')); assert.ok(!code.includes('httpx\\n'));
 await page.keyboard.press('Escape');
 await page.setViewportSize({width:390,height:844});
 await page.getByRole('button',{name:'订阅渠道',exact:true}).click();
 await page.getByRole('heading',{name:'新闻联播服务',exact:true}).waitFor();
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));
 await page.screenshot({path:'.trellis/tasks/10-09-rss-channel-feeds/mobile.png',fullPage:true});
 await page.setViewportSize({width:1280,height:900});
 await page.screenshot({path:'.trellis/tasks/10-09-rss-channel-feeds/desktop.png',fullPage:true});
 await page.evaluate(()=>Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async()=>{throw new Error('denied')}}}));
 await page.getByRole('button',{name:'复制链接',exact:true}).first().click();
 await page.getByLabel('手动复制内容').waitFor();
 await page.keyboard.press('Escape');
 assert.equal(await page.evaluate(()=>document.activeElement.textContent),'订阅渠道');
 assert.deepEqual(errors,[]);
 console.log('PASS: create/edit/disable/restore, channel copy, dynamic Python guide, mobile layout, clipboard fallback, focus restore');
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
